//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Có  .
        /// </summary>
        internal static string btnCo {
            get {
                return ResourceManager.GetString("btnCo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Co  .
        /// </summary>
        internal static string btnCo_KD {
            get {
                return ResourceManager.GetString("btnCo_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Không .
        /// </summary>
        internal static string btnKhong {
            get {
                return ResourceManager.GetString("btnKhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Khong .
        /// </summary>
        internal static string btnKhong_KD {
            get {
                return ResourceManager.GetString("btnKhong_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAME CÙNG THỂ LOẠI.
        /// </summary>
        internal static string gGameCungTheLoai {
            get {
                return ResourceManager.GetString("gGameCungTheLoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAME CUNG THE LOAI.
        /// </summary>
        internal static string gGameCungTheLoai_KD {
            get {
                return ResourceManager.GetString("gGameCungTheLoai_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THỂ LOẠI GAME.
        /// </summary>
        internal static string gTheLoaiGame {
            get {
                return ResourceManager.GetString("gTheLoaiGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE LOAI GAME.
        /// </summary>
        internal static string gTheLoaiGame_KD {
            get {
                return ResourceManager.GetString("gTheLoaiGame_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HÌNH NỀN CÙNG THỂ LOẠI.
        /// </summary>
        internal static string hnHinhCungTheLoai {
            get {
                return ResourceManager.GetString("hnHinhCungTheLoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HINH NEN CUNG THE LOAI.
        /// </summary>
        internal static string hnHinhCungTheLoai_KD {
            get {
                return ResourceManager.GetString("hnHinhCungTheLoai_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THỂ LOẠI HÌNH NỀN.
        /// </summary>
        internal static string hnTheLoaiHinh {
            get {
                return ResourceManager.GetString("hnTheLoaiHinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE LOAI HINH NEN.
        /// </summary>
        internal static string hnTheLoaiHinh_KD {
            get {
                return ResourceManager.GetString("hnTheLoaiHinh_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHẦN MỀM CÙNG THỂ LOẠI.
        /// </summary>
        internal static string pmPhanMemCungTheLoai {
            get {
                return ResourceManager.GetString("pmPhanMemCungTheLoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHAN MEM CUNG THE LOAI.
        /// </summary>
        internal static string pmPhanMemCungTheLoai_KD {
            get {
                return ResourceManager.GetString("pmPhanMemCungTheLoai_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THỂ LOẠI PHẦN MỀM.
        /// </summary>
        internal static string pmTheLoaiPhanMem {
            get {
                return ResourceManager.GetString("pmTheLoaiPhanMem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE LOAI PHAN MEM.
        /// </summary>
        internal static string pmTheLoaiPhanMem_KD {
            get {
                return ResourceManager.GetString("pmTheLoaiPhanMem_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHẠC CÙNG THỂ LOẠI.
        /// </summary>
        internal static string rNhacCungTheLoai {
            get {
                return ResourceManager.GetString("rNhacCungTheLoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHAC CUNG THE LOAI.
        /// </summary>
        internal static string rNhacCungTheLoai_KD {
            get {
                return ResourceManager.GetString("rNhacCungTheLoai_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THỂ LOẠI NHẠC.
        /// </summary>
        internal static string rTheLoaiNhac {
            get {
                return ResourceManager.GetString("rTheLoaiNhac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE LOAI NHAC.
        /// </summary>
        internal static string rTheLoaiNhac_KD {
            get {
                return ResourceManager.GetString("rTheLoaiNhac_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHỦ ĐỀ HOT.
        /// </summary>
        internal static string tgChuDeHot {
            get {
                return ResourceManager.GetString("tgChuDeHot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHU DE HOT.
        /// </summary>
        internal static string tgChuDeHot_KD {
            get {
                return ResourceManager.GetString("tgChuDeHot_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THỂ LOẠI VIDEO.
        /// </summary>
        internal static string vTheLoaiVideo {
            get {
                return ResourceManager.GetString("vTheLoaiVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE LOAI VIDEO.
        /// </summary>
        internal static string vTheLoaiVideo_KD {
            get {
                return ResourceManager.GetString("vTheLoaiVideo_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIDEO CÙNG THỂ LOẠI.
        /// </summary>
        internal static string vVideoCungTheLoai {
            get {
                return ResourceManager.GetString("vVideoCungTheLoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIDEO CUNG THE LOAI.
        /// </summary>
        internal static string vVideoCungTheLoai_KD {
            get {
                return ResourceManager.GetString("vVideoCungTheLoai_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span style=&quot;color:#0000FF; text-decoration:underline&quot;&gt;Bấm vào đây để tải nội dung về máy&lt;/span&gt;.
        /// </summary>
        internal static string wBamDeTai {
            get {
                return ResourceManager.GetString("wBamDeTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span style=&quot;color:#0000FF; text-decoration:underline&quot;&gt;Bam vao day de tai noi dung ve may&lt;/span&gt;.
        /// </summary>
        internal static string wBamDeTai_KD {
            get {
                return ResourceManager.GetString("wBamDeTai_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span style=&quot;color:#0000FF; text-decoration:underline&quot;&gt;Bấm vào đây để xem &lt;/spanont&gt;.
        /// </summary>
        internal static string wBamDeXem {
            get {
                return ResourceManager.GetString("wBamDeXem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span style=&quot;color:#0000FF; text-decoration:underline&quot;&gt;Bam vao day de xem &lt;/span&gt;.
        /// </summary>
        internal static string wBamDeXem_KD {
            get {
                return ResourceManager.GetString("wBamDeXem_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÁC GIẢI ĐẤU.
        /// </summary>
        internal static string wCacGiaiDau {
            get {
                return ResourceManager.GetString("wCacGiaiDau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAC GIAI DAU.
        /// </summary>
        internal static string wCacGiaiDau_KD {
            get {
                return ResourceManager.GetString("wCacGiaiDau_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca sỹ: .
        /// </summary>
        internal static string wCaSy {
            get {
                return ResourceManager.GetString("wCaSy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca sy: .
        /// </summary>
        internal static string wCaSy_KD {
            get {
                return ResourceManager.GetString("wCaSy_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br /&gt;Vui lòng chọn kết nối EDGE/3G để sử dụng dịch vụ này qua WAP..
        /// </summary>
        internal static string wChon3G {
            get {
                return ResourceManager.GetString("wChon3G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br /&gt;Vui long chon ket noi EDGE/3G de su dung dich vu nay qua WAP..
        /// </summary>
        internal static string wChon3G_KD {
            get {
                return ResourceManager.GetString("wChon3G_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  đ.
        /// </summary>
        internal static string wDonViTien {
            get {
                return ResourceManager.GetString("wDonViTien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  d.
        /// </summary>
        internal static string wDonViTien_KD {
            get {
                return ResourceManager.GetString("wDonViTien_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá: .
        /// </summary>
        internal static string wGia {
            get {
                return ResourceManager.GetString("wGia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá tải: .
        /// </summary>
        internal static string wGiaTai {
            get {
                return ResourceManager.GetString("wGiaTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gia tai: .
        /// </summary>
        internal static string wGiaTai_KD {
            get {
                return ResourceManager.GetString("wGiaTai_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá tặng: .
        /// </summary>
        internal static string wGiaTang {
            get {
                return ResourceManager.GetString("wGiaTang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gia tang: .
        /// </summary>
        internal static string wGiaTang_KD {
            get {
                return ResourceManager.GetString("wGiaTang_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gia: .
        /// </summary>
        internal static string wGia_KD {
            get {
                return ResourceManager.GetString("wGia_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới thiệu: .
        /// </summary>
        internal static string wGioiThieu {
            get {
                return ResourceManager.GetString("wGioiThieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gioi thieu: .
        /// </summary>
        internal static string wGioiThieu_KD {
            get {
                return ResourceManager.GetString("wGioiThieu_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi tặng.
        /// </summary>
        internal static string wGuiTang {
            get {
                return ResourceManager.GetString("wGuiTang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gui tang.
        /// </summary>
        internal static string wGuiTang_KD {
            get {
                return ResourceManager.GetString("wGuiTang_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HƯỚNG DẪN.
        /// </summary>
        internal static string wHuongDan {
            get {
                return ResourceManager.GetString("wHuongDan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUONG DAN.
        /// </summary>
        internal static string wHuongDan_KD {
            get {
                return ResourceManager.GetString("wHuongDan_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không hỗ trợ.
        /// </summary>
        internal static string wKhongHoTro {
            get {
                return ResourceManager.GetString("wKhongHoTro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khong ho tro.
        /// </summary>
        internal static string wKhongHoTro_KD {
            get {
                return ResourceManager.GetString("wKhongHoTro_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lượt tải: .
        /// </summary>
        internal static string wLuotTai {
            get {
                return ResourceManager.GetString("wLuotTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luot tai: .
        /// </summary>
        internal static string wLuotTai_KD {
            get {
                return ResourceManager.GetString("wLuotTai_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lượt xem: .
        /// </summary>
        internal static string wLuotXem {
            get {
                return ResourceManager.GetString("wLuotXem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luot xem: .
        /// </summary>
        internal static string wLuotXem_KD {
            get {
                return ResourceManager.GetString("wLuotXem_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MỚI CẬP NHẬT.
        /// </summary>
        internal static string wMoiCapNhat {
            get {
                return ResourceManager.GetString("wMoiCapNhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOI CAP NHAT.
        /// </summary>
        internal static string wMoiCapNhat_KD {
            get {
                return ResourceManager.GetString("wMoiCapNhat_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã mua thành công.
        /// </summary>
        internal static string wMuaThanhCong {
            get {
                return ResourceManager.GetString("wMuaThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban da mua thanh cong.
        /// </summary>
        internal static string wMuaThanhCong_KD {
            get {
                return ResourceManager.GetString("wMuaThanhCong_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số bài: .
        /// </summary>
        internal static string wSoBai {
            get {
                return ResourceManager.GetString("wSoBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So bai: .
        /// </summary>
        internal static string wSoBai_KD {
            get {
                return ResourceManager.GetString("wSoBai_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại bạn gửi tặng không hợp lệ.&lt;br /&gt;Vui lòng kiểm tra lại..
        /// </summary>
        internal static string wSoDienThoaiKhongHopLe {
            get {
                return ResourceManager.GetString("wSoDienThoaiKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So dien thoai ban gui tang khong hop le.&lt;br /&gt;Vui long kiem tra lai..
        /// </summary>
        internal static string wSoDienThoaiKhongHopLe_KD {
            get {
                return ResourceManager.GetString("wSoDienThoaiKhongHopLe_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải.
        /// </summary>
        internal static string wTai {
            get {
                return ResourceManager.GetString("wTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TẢI NHIỀU NHẤT.
        /// </summary>
        internal static string wTaiNhieuNhat {
            get {
                return ResourceManager.GetString("wTaiNhieuNhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAI NHIEU NHAT.
        /// </summary>
        internal static string wTaiNhieuNhat_KD {
            get {
                return ResourceManager.GetString("wTaiNhieuNhat_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải về.
        /// </summary>
        internal static string wTaiVe {
            get {
                return ResourceManager.GetString("wTaiVe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tai ve.
        /// </summary>
        internal static string wTaiVe_KD {
            get {
                return ResourceManager.GetString("wTaiVe_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tai.
        /// </summary>
        internal static string wTai_KD {
            get {
                return ResourceManager.GetString("wTai_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tặng.
        /// </summary>
        internal static string wTang {
            get {
                return ResourceManager.GetString("wTang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã gửi tặng thành công.
        /// </summary>
        internal static string wTangThanhCong {
            get {
                return ResourceManager.GetString("wTangThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban da gui tang thanh cong.
        /// </summary>
        internal static string wTangThanhCong_KD {
            get {
                return ResourceManager.GetString("wTangThanhCong_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tang.
        /// </summary>
        internal static string wTang_KD {
            get {
                return ResourceManager.GetString("wTang_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thể loại: .
        /// </summary>
        internal static string wTheLoai {
            get {
                return ResourceManager.GetString("wTheLoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loai: .
        /// </summary>
        internal static string wTheLoai_KD {
            get {
                return ResourceManager.GetString("wTheLoai_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THÔNG BÁO.
        /// </summary>
        internal static string wThongBao {
            get {
                return ResourceManager.GetString("wThongBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá: .
        /// </summary>
        internal static string wThongBaoGia {
            get {
                return ResourceManager.GetString("wThongBaoGia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gia: .
        /// </summary>
        internal static string wThongBaoGia_KD {
            get {
                return ResourceManager.GetString("wThongBaoGia_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lệnh thanh toán không thành công hoặc tài khoản không đủ tiền.&lt;br /&gt;Bạn vui lòng kiểm tra lại tài khoản và thử lại sau.&lt;br /&gt;Xin cảm ơn..
        /// </summary>
        internal static string wThongBaoLoiThanhToan {
            get {
                return ResourceManager.GetString("wThongBaoLoiThanhToan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenh thanh toan khong thanh cong hoac tai khoan khong du tien.&lt;br /&gt;Ban vui long kiem tra lai tai khoan va thu lai sau.&lt;br /&gt;Xin cam on..
        /// </summary>
        internal static string wThongBaoLoiThanhToan_KD {
            get {
                return ResourceManager.GetString("wThongBaoLoiThanhToan_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THONG BAO.
        /// </summary>
        internal static string wThongBao_KD {
            get {
                return ResourceManager.GetString("wThongBao_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        internal static string wTrangChu {
            get {
                return ResourceManager.GetString("wTrangChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chu.
        /// </summary>
        internal static string wTrangChu_KD {
            get {
                return ResourceManager.GetString("wTrangChu_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn vui lòng xác nhận trước khi đăng ký .
        /// </summary>
        internal static string wXacNhanDangKyDichVu {
            get {
                return ResourceManager.GetString("wXacNhanDangKyDichVu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban vui long xac nhan truoc khi dang ky .
        /// </summary>
        internal static string wXacNhanDangKyDichVu_KD {
            get {
                return ResourceManager.GetString("wXacNhanDangKyDichVu_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn vui lòng xác nhận trước khi tải .
        /// </summary>
        internal static string wXacNhanDichVu {
            get {
                return ResourceManager.GetString("wXacNhanDichVu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban vui long xac nhan truoc khi tai .
        /// </summary>
        internal static string wXacNhanDichVu_KD {
            get {
                return ResourceManager.GetString("wXacNhanDichVu_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đồng ý mua.
        /// </summary>
        internal static string wXacNhanNoiDung {
            get {
                return ResourceManager.GetString("wXacNhanNoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban dong y mua.
        /// </summary>
        internal static string wXacNhanNoiDung_KD {
            get {
                return ResourceManager.GetString("wXacNhanNoiDung_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn vui lòng xác nhận trước khi tặng .
        /// </summary>
        internal static string wXacNhanTangDichVu {
            get {
                return ResourceManager.GetString("wXacNhanTangDichVu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban vui long xac nhan truoc khi tang .
        /// </summary>
        internal static string wXacNhanTangDichVu_KD {
            get {
                return ResourceManager.GetString("wXacNhanTangDichVu_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÁC TỈNH MỞ THƯỞNG.
        /// </summary>
        internal static string xsCacTinhMoThuong {
            get {
                return ResourceManager.GetString("xsCacTinhMoThuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAC TINH Mo THUONG.
        /// </summary>
        internal static string xsCacTinhMoThuong_KD {
            get {
                return ResourceManager.GetString("xsCacTinhMoThuong_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;orange bold&quot;&gt;KQ chờ&lt;/span&gt;.
        /// </summary>
        internal static string xsKQCho {
            get {
                return ResourceManager.GetString("xsKQCho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;orange bold&quot;&gt;KQ cho&lt;/span&gt;.
        /// </summary>
        internal static string xsKQCho_KD {
            get {
                return ResourceManager.GetString("xsKQCho_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KQ.
        /// </summary>
        internal static string xsKQKyTruoc {
            get {
                return ResourceManager.GetString("xsKQKyTruoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KQ.
        /// </summary>
        internal static string xsKQKyTruoc_KD {
            get {
                return ResourceManager.GetString("xsKQKyTruoc_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;orange bold&quot;&gt;Soi cầu&lt;/span&gt;.
        /// </summary>
        internal static string xsSoiCau {
            get {
                return ResourceManager.GetString("xsSoiCau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;orange bold&quot;&gt;Soi cau&lt;/span&gt;.
        /// </summary>
        internal static string xsSoiCau_KD {
            get {
                return ResourceManager.GetString("xsSoiCau_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XS Thủ đô.
        /// </summary>
        internal static string xsXSThuDo {
            get {
                return ResourceManager.GetString("xsXSThuDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XS Thu do.
        /// </summary>
        internal static string xsXSThuDo_KD {
            get {
                return ResourceManager.GetString("xsXSThuDo_KD", resourceCulture);
            }
        }
    }
}
