//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wap_TheThaoSo.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://123.29.68.131:8007/GetAvatarThumb.asmx")]
        public string Wap_TheThaoSo_WapTheThaoSoWebReference_GetAvatarThumb {
            get {
                return ((string)(this["Wap_TheThaoSo_WapTheThaoSoWebReference_GetAvatarThumb"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://123.29.68.131:8009/GetAvatarThumb.asmx")]
        public string Wap_TheThaoSo_TinTucWebReference_GetAvatarThumb {
            get {
                return ((string)(this["Wap_TheThaoSo_TinTucWebReference_GetAvatarThumb"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://payment.xzone.vn/srti.asmx")]
        public string Wap_TheThaoSo_vn_xzone_payment_srti {
            get {
                return ((string)(this["Wap_TheThaoSo_vn_xzone_payment_srti"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://media.xzone.vn:8094/MOReceiver.asmx")]
        public string Wap_TheThaoSo_vn_xzone_media_MOReceiver {
            get {
                return ((string)(this["Wap_TheThaoSo_vn_xzone_media_MOReceiver"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sv36.vmgmedia.vn:9203/WebServiceCharging3g.asmx")]
        public string Wap_TheThaoSo_VnmCharging_WebServiceCharging3g {
            get {
                return ((string)(this["Wap_TheThaoSo_VnmCharging_WebServiceCharging3g"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.168.33:8080/api/services/sendMT")]
        public string Wap_TheThaoSo_SentMT_ServiceProviderService {
            get {
                return ((string)(this["Wap_TheThaoSo_SentMT_ServiceProviderService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sv167.vmgmedia.vn:8000/WebService.asmx")]
        public string Wap_TheThaoSo_WSVisport_WebService {
            get {
                return ((string)(this["Wap_TheThaoSo_WSVisport_WebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sv167.vmgmedia.vn:8000/WebService.asmx")]
        public string Wap_TheThaoSo_WS_ViSport_WebService {
            get {
                return ((string)(this["Wap_TheThaoSo_WS_ViSport_WebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://vmgame.vn/Service_RegisS2.asmx")]
        public string Wap_TheThaoSo_Vmgame_Service_RegisS2 {
            get {
                return ((string)(this["Wap_TheThaoSo_Vmgame_Service_RegisS2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sv36.vmgmedia.vn:9005/S2Vnm.asmx")]
        public string Wap_TheThaoSo_WS_94x_S2Vnm {
            get {
                return ((string)(this["Wap_TheThaoSo_WS_94x_S2Vnm"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sv167.vmgmedia.vn:8000/Euro.asmx")]
        public string Wap_TheThaoSo_WS_Euro2016_Euro {
            get {
                return ((string)(this["Wap_TheThaoSo_WS_Euro2016_Euro"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://vmgame.vn:8001/MsisdnService.asmx")]
        public string Wap_TheThaoSo_MsisdnService_MsisdnService {
            get {
                return ((string)(this["Wap_TheThaoSo_MsisdnService_MsisdnService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sv167.vmgmedia.vn:9001/VnmVsp.asmx")]
        public string Wap_TheThaoSo_VisportNew_VnmVsp {
            get {
                return ((string)(this["Wap_TheThaoSo_VisportNew_VnmVsp"]));
            }
        }
    }
}
