//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace Wap_TheThaoSo.Vmgame {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service_RegisS2Soap", Namespace="http://tempuri.org/")]
    public partial class Service_RegisS2 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RegisterS2OperationCompleted;
        
        private System.Threading.SendOrPostCallback RegisterS2NewOperationCompleted;
        
        private System.Threading.SendOrPostCallback BigPromotionRegisOperationCompleted;
        
        private System.Threading.SendOrPostCallback BigPromotionDeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegisApiOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteApiOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service_RegisS2() {
            this.Url = global::Wap_TheThaoSo.Properties.Settings.Default.Wap_TheThaoSo_Vmgame_Service_RegisS2;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RegisterS2CompletedEventHandler RegisterS2Completed;
        
        /// <remarks/>
        public event RegisterS2NewCompletedEventHandler RegisterS2NewCompleted;
        
        /// <remarks/>
        public event BigPromotionRegisCompletedEventHandler BigPromotionRegisCompleted;
        
        /// <remarks/>
        public event BigPromotionDeleteCompletedEventHandler BigPromotionDeleteCompleted;
        
        /// <remarks/>
        public event RegisApiCompletedEventHandler RegisApiCompleted;
        
        /// <remarks/>
        public event DeleteApiCompletedEventHandler DeleteApiCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegisterS2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RegisterS2(string msisdn) {
            object[] results = this.Invoke("RegisterS2", new object[] {
                        msisdn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RegisterS2Async(string msisdn) {
            this.RegisterS2Async(msisdn, null);
        }
        
        /// <remarks/>
        public void RegisterS2Async(string msisdn, object userState) {
            if ((this.RegisterS2OperationCompleted == null)) {
                this.RegisterS2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterS2OperationCompleted);
            }
            this.InvokeAsync("RegisterS2", new object[] {
                        msisdn}, this.RegisterS2OperationCompleted, userState);
        }
        
        private void OnRegisterS2OperationCompleted(object arg) {
            if ((this.RegisterS2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterS2Completed(this, new RegisterS2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegisterS2New", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RegisterS2New(string msisdn, System.DateTime day) {
            object[] results = this.Invoke("RegisterS2New", new object[] {
                        msisdn,
                        day});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RegisterS2NewAsync(string msisdn, System.DateTime day) {
            this.RegisterS2NewAsync(msisdn, day, null);
        }
        
        /// <remarks/>
        public void RegisterS2NewAsync(string msisdn, System.DateTime day, object userState) {
            if ((this.RegisterS2NewOperationCompleted == null)) {
                this.RegisterS2NewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterS2NewOperationCompleted);
            }
            this.InvokeAsync("RegisterS2New", new object[] {
                        msisdn,
                        day}, this.RegisterS2NewOperationCompleted, userState);
        }
        
        private void OnRegisterS2NewOperationCompleted(object arg) {
            if ((this.RegisterS2NewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterS2NewCompleted(this, new RegisterS2NewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BigPromotionRegis", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BigPromotionRegis(string msisdn, string code) {
            object[] results = this.Invoke("BigPromotionRegis", new object[] {
                        msisdn,
                        code});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BigPromotionRegisAsync(string msisdn, string code) {
            this.BigPromotionRegisAsync(msisdn, code, null);
        }
        
        /// <remarks/>
        public void BigPromotionRegisAsync(string msisdn, string code, object userState) {
            if ((this.BigPromotionRegisOperationCompleted == null)) {
                this.BigPromotionRegisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBigPromotionRegisOperationCompleted);
            }
            this.InvokeAsync("BigPromotionRegis", new object[] {
                        msisdn,
                        code}, this.BigPromotionRegisOperationCompleted, userState);
        }
        
        private void OnBigPromotionRegisOperationCompleted(object arg) {
            if ((this.BigPromotionRegisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BigPromotionRegisCompleted(this, new BigPromotionRegisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BigPromotionDelete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BigPromotionDelete(string msisdn, string code) {
            object[] results = this.Invoke("BigPromotionDelete", new object[] {
                        msisdn,
                        code});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BigPromotionDeleteAsync(string msisdn, string code) {
            this.BigPromotionDeleteAsync(msisdn, code, null);
        }
        
        /// <remarks/>
        public void BigPromotionDeleteAsync(string msisdn, string code, object userState) {
            if ((this.BigPromotionDeleteOperationCompleted == null)) {
                this.BigPromotionDeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBigPromotionDeleteOperationCompleted);
            }
            this.InvokeAsync("BigPromotionDelete", new object[] {
                        msisdn,
                        code}, this.BigPromotionDeleteOperationCompleted, userState);
        }
        
        private void OnBigPromotionDeleteOperationCompleted(object arg) {
            if ((this.BigPromotionDeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BigPromotionDeleteCompleted(this, new BigPromotionDeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegisApi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RegisApi(string msisdn, string commandCode, string requestId, int serviceType, string code, string content, int ngayhuy) {
            object[] results = this.Invoke("RegisApi", new object[] {
                        msisdn,
                        commandCode,
                        requestId,
                        serviceType,
                        code,
                        content,
                        ngayhuy});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RegisApiAsync(string msisdn, string commandCode, string requestId, int serviceType, string code, string content, int ngayhuy) {
            this.RegisApiAsync(msisdn, commandCode, requestId, serviceType, code, content, ngayhuy, null);
        }
        
        /// <remarks/>
        public void RegisApiAsync(string msisdn, string commandCode, string requestId, int serviceType, string code, string content, int ngayhuy, object userState) {
            if ((this.RegisApiOperationCompleted == null)) {
                this.RegisApiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisApiOperationCompleted);
            }
            this.InvokeAsync("RegisApi", new object[] {
                        msisdn,
                        commandCode,
                        requestId,
                        serviceType,
                        code,
                        content,
                        ngayhuy}, this.RegisApiOperationCompleted, userState);
        }
        
        private void OnRegisApiOperationCompleted(object arg) {
            if ((this.RegisApiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisApiCompleted(this, new RegisApiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteApi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DeleteApi(string msisdn, int serviceType, string code) {
            object[] results = this.Invoke("DeleteApi", new object[] {
                        msisdn,
                        serviceType,
                        code});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteApiAsync(string msisdn, int serviceType, string code) {
            this.DeleteApiAsync(msisdn, serviceType, code, null);
        }
        
        /// <remarks/>
        public void DeleteApiAsync(string msisdn, int serviceType, string code, object userState) {
            if ((this.DeleteApiOperationCompleted == null)) {
                this.DeleteApiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteApiOperationCompleted);
            }
            this.InvokeAsync("DeleteApi", new object[] {
                        msisdn,
                        serviceType,
                        code}, this.DeleteApiOperationCompleted, userState);
        }
        
        private void OnDeleteApiOperationCompleted(object arg) {
            if ((this.DeleteApiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteApiCompleted(this, new DeleteApiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void RegisterS2CompletedEventHandler(object sender, RegisterS2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegisterS2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegisterS2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void RegisterS2NewCompletedEventHandler(object sender, RegisterS2NewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegisterS2NewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegisterS2NewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void BigPromotionRegisCompletedEventHandler(object sender, BigPromotionRegisCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BigPromotionRegisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BigPromotionRegisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void BigPromotionDeleteCompletedEventHandler(object sender, BigPromotionDeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BigPromotionDeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BigPromotionDeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void RegisApiCompletedEventHandler(object sender, RegisApiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegisApiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegisApiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DeleteApiCompletedEventHandler(object sender, DeleteApiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteApiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteApiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591