//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace Wap_TheThaoSo.WS_Euro2016 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EuroSoap", Namespace="http://tempuri.org/")]
    public partial class Euro : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback WSProcessMoSportGameOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSProcessMoEuro_WapOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Euro() {
            this.Url = global::Wap_TheThaoSo.Properties.Settings.Default.Wap_TheThaoSo_WS_Euro2016_Euro;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event WSProcessMoSportGameCompletedEventHandler WSProcessMoSportGameCompleted;
        
        /// <remarks/>
        public event WSProcessMoEuro_WapCompletedEventHandler WSProcessMoEuro_WapCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSProcessMoSportGame", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WSProcessMoSportGame(string User_ID, string Service_ID, string Command_Code, string Message, string Request_ID) {
            object[] results = this.Invoke("WSProcessMoSportGame", new object[] {
                        User_ID,
                        Service_ID,
                        Command_Code,
                        Message,
                        Request_ID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WSProcessMoSportGameAsync(string User_ID, string Service_ID, string Command_Code, string Message, string Request_ID) {
            this.WSProcessMoSportGameAsync(User_ID, Service_ID, Command_Code, Message, Request_ID, null);
        }
        
        /// <remarks/>
        public void WSProcessMoSportGameAsync(string User_ID, string Service_ID, string Command_Code, string Message, string Request_ID, object userState) {
            if ((this.WSProcessMoSportGameOperationCompleted == null)) {
                this.WSProcessMoSportGameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSProcessMoSportGameOperationCompleted);
            }
            this.InvokeAsync("WSProcessMoSportGame", new object[] {
                        User_ID,
                        Service_ID,
                        Command_Code,
                        Message,
                        Request_ID}, this.WSProcessMoSportGameOperationCompleted, userState);
        }
        
        private void OnWSProcessMoSportGameOperationCompleted(object arg) {
            if ((this.WSProcessMoSportGameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSProcessMoSportGameCompleted(this, new WSProcessMoSportGameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSProcessMoEuro_Wap", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WSProcessMoEuro_Wap(string User_ID, string Service_ID, string Command_Code, string Message, string Request_ID) {
            object[] results = this.Invoke("WSProcessMoEuro_Wap", new object[] {
                        User_ID,
                        Service_ID,
                        Command_Code,
                        Message,
                        Request_ID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WSProcessMoEuro_WapAsync(string User_ID, string Service_ID, string Command_Code, string Message, string Request_ID) {
            this.WSProcessMoEuro_WapAsync(User_ID, Service_ID, Command_Code, Message, Request_ID, null);
        }
        
        /// <remarks/>
        public void WSProcessMoEuro_WapAsync(string User_ID, string Service_ID, string Command_Code, string Message, string Request_ID, object userState) {
            if ((this.WSProcessMoEuro_WapOperationCompleted == null)) {
                this.WSProcessMoEuro_WapOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSProcessMoEuro_WapOperationCompleted);
            }
            this.InvokeAsync("WSProcessMoEuro_Wap", new object[] {
                        User_ID,
                        Service_ID,
                        Command_Code,
                        Message,
                        Request_ID}, this.WSProcessMoEuro_WapOperationCompleted, userState);
        }
        
        private void OnWSProcessMoEuro_WapOperationCompleted(object arg) {
            if ((this.WSProcessMoEuro_WapCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSProcessMoEuro_WapCompleted(this, new WSProcessMoEuro_WapCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void WSProcessMoSportGameCompletedEventHandler(object sender, WSProcessMoSportGameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSProcessMoSportGameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSProcessMoSportGameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void WSProcessMoEuro_WapCompletedEventHandler(object sender, WSProcessMoEuro_WapCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSProcessMoEuro_WapCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSProcessMoEuro_WapCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591